### ISSUE TITLE
ReelSteady-Joiner

### ISSUE THREAD

**Issue by Nilssonfpv** [rubegartor/ReelSteady-Joiner#1]
Hi

Loving how well this works for merging together chapters, but it is making it a bit harder to manage my gopro files.
Is there any way you could preserve the original modified date on the output file, and preferably initial fine name to (perhaps with a _Joined suffix)?
I use the datestamp to figure out when a specific clip was shot at events.

Here's how to do it with the commandline on Windows.
https://www.winhelponline.com/blog/change-accessed-modified-created-file-date-timestamp-windows/

Secondly, id love for a "batch" convert option, where i can just point it at a folder and it looks for files following Gopros file naming convention.

**Comment by rubegartor** [comment]
Hi
Your ideas seem quite interesting to me. I am currently refactoring the code and trying to give support for Linux and Mac. Moreover, I also plan to add an options tab where you will be able to customize various aspects and therefore these ideas you are talking about can be integrated in this tab. I'm going to create a PR to work on these ideas and try to launch them in the next version. Any ideas and contributions are always welcome.

Greetings and thanks for your interest!

**Comment by chuck-buckets** [comment]
This is such an amazing tool. I've been looking for something like this FOREVER. My issue is similar to what you mentioned above. I have a windows laptop but it has like 4GB of available memory (even if I delete everything), so that's super annoying. But if I could change the output to write to a removable drive that would solve my problem. Or if support for mac were available! Thanks again for your work. This will change lives!

**Comment by rubegartor** [comment]
Hi! it's expected that in the next few days a beta version will be released with all the new changes that have been proposed, including the options for the automatic search of chapters or the selection of the path where the project is saved. I advise you to check these next few days waiting for updates, when you open the application it will appear that there is an update available.

At the moment it will be a beta version until it is proven that everything works correctly, so it may contain errors.

**About Mac Os support**: I'm working on it but it is not confirmed yet.
**About Linux support**: Possibly not supported.

**Comment by Arvycka** [comment]
I there a (paypal) donation link on your github page somewhere?

2021 m. rugs. 16 d., kt 18:15, Rubén ***@***.***> rašė:

**Comment by rubegartor** [comment]
Hi, I have added the paypal donation button to README.
Thanks.

**Comment by Nilssonfpv** [comment]
> Hi! it's expected that in the next few days a beta version will be released with all the new changes that have been proposed, including the options for the automatic search of chapters or the selection of the path where the project is saved. I advise you to check these next few days waiting for updates.


Awesome, on a side note. Could it name the files datetime_originalfilename.mov as well, instead of just updating timestamps as i originally suggested? Bonus points if it can do that for an entire folder even if its only merging some of the files.

**Comment by rubegartor** [comment]
> > Hi! it's expected that in the next few days a beta version will be released with all the new changes that have been proposed, including the options for the automatic search of chapters or the selection of the path where the project is saved. I advise you to check these next few days waiting for updates.
> 
> Awesome, on a side note. Could it name the files datetime_originalfilename.mov as well, instead of just updating timestamps as i originally suggested? Bonus points if it can do that for an entire folder even if its only merging some of the files.

The name of the output file has been changed, from the new version it is used: [name of the original file] _joined.mp4. (As you suggested in the issue)
The folder containing this file has also been renamed, now the modified date of the original file is used.

Maybe for future updates I will look for a way to be able to customize the name of the file.
The modification date of the original file has been added to the file generated by ReelSteady Joiner. (As you suggested in the issue)

As a clarification, ReelSteady Joiner is currently only capable of processing MP4 files

Hope the new features help.

(If you have any questions not related to this issue, do not hesitate to contact me via e-mail)

**Comment by rubegartor** [comment]
### ReelSteady v1.2.0-beta is available in Releases Tab
If any error is found, I would be grateful to report it so that it can be corrected.
Thanks!
