### ISSUE TITLE
error mp4 file not valid Gopro10

### ISSUE THREAD

**Issue by geoscanna** [rubegartor/ReelSteady-Joiner#10]
**Describe the bug**
i uploaded two .mp4 clips which generated my gopro. the software returns the error because it does not recognize the mp4 file as a file generated by the gopro

**To Reproduce**
select file and merge 
Error: mp4 file not valid

**Desktop (please complete the following information):**
 - OS: WIndows 10
 
**GoPro camera and files information**
(If applicable)
- GoPro Model: gopro10
- GoPro Files info: 4k 4/3 

![Screenshot_2](https://user-images.githubusercontent.com/95127131/143678417-23f2399d-8ebf-4eac-972d-50261319db8d.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/95127131/143678415-866675e9-7172-4314-8a96-3f8457389bbe.jpg)
.
[27 nov 2021 12-00.log](https://github.com/rubegartor/ReelSteady-Joiner/files/7611614/27.nov.2021.12-00.log)

**[IMPORTANT] Logs (attach log file)**

**Comment by rubegartor** [comment]
Hello, thank you for providing all the information. I've reviewed the log files that you've attached, I've seen that it doesn't detect part of the metadata, perhaps in the new video files for the GoPro 10 it's not included, I don't have this model, the tests I did to develop ReelSteady Joiner were with a GoPro Hero 6 Black and a GoPro Hero 9, I've compiled a trial version removing the GoPro file check, if with this version you can perform the process, please, let me know to update ReelSteady Joiner.

If there is any way to obtain test files made with GoPro Hero 10 I would greatly appreciate it to be able to carry out tests, you can contact me through my email: rubegartor@gmail.com.

Download ReelSteady Joiner v1.2.3-alpha: [https://drive.google.com/file/d/1r1VjKvrMLtdH3BiuKdiNaQaPhRXuEtPW](https://drive.google.com/file/d/1r1VjKvrMLtdH3BiuKdiNaQaPhRXuEtPW)

Regards, and thank you very much.

**Comment by geoscanna** [comment]
Hi, I downloaded version v1.2.3 and tried to run the files. the process continues creating the merge folder, but inside it does not create the .mp4 merge file.
I'm sending you the log file
good day
[29 nov 2021 08-57.log](https://github.com/rubegartor/ReelSteady-Joiner/files/7616484/29.nov.2021.08-57.log)
y

**Comment by rubegartor** [comment]
Hi, I've checked the log file you attached, it's the same problem, it does not detect the part that contains the gyroscope data in the video file, I start to think that the problem may be related to your files and not ReelSteady Joiner. Is there an option to get a clip recorded with your camera? I do not need anything special, only that it is recorded with correct settings for later use in ReelSteady, with a few seconds of video it would be enough only to review the video file and the data.

I've gotten video files from a GoPro Hero 10 and these contained the necessary gyro data in the file, it's strange that your files don't have it.

Anyway, could you specify the following information ?:
- How have you extracted the videos from the GoPro?
- Could your antivirus be interfering with the process?
- Have you previously edited those files with any other program?

Thanks.
