### ISSUE TITLE
Doesn't work on external SSD/HDD

### ISSUE THREAD

**Issue by matteleon** [rubegartor/ReelSteady-Joiner#13]
**Describe the bug**
Reelsteady Joiner won't join GoPro chapters stored on an SSD/HDD. 

**To Reproduce**
Open files you want to join on RS Joiner that are stored on an external SSD. Merge. Software says finished but no file.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 12.0.1

**GoPro camera and files information**
(If applicable)
- GoPro Model: GoPro Hero 10
- GoPro Files info: They are normal chapters

**Comment by rubegartor** [comment]
Hi, apparently it's a known problem but I haven't been able to identify it yet, could you attach the log files?
To find the log files you can do it in the following way: Settings > Logs > Open Logs, and attach the log files corresponding to your attempts.

Without them it is impossible for me to continue investigating this problem.

Thanks.

**Comment by matteleon** [comment]
[14 Mar 2022 17-36.log](https://github.com/rubegartor/ReelSteady-Joiner/files/8247279/14.Mar.2022.17-36.log)

**Comment by rubegartor** [comment]
I have released a new version of [ReelSteady Joiner (v1.2.4)](https://github.com/rubegartor/ReelSteady-Joiner/releases/tag/v.1.2.4) correcting the problem.
If this has solved the problem I would appreciate confirmation.

**Comment by matteleon** [comment]
Fixed, thank you! Working on external SSD.
