### ISSUE TITLE
CLI Version

### ISSUE THREAD

**Issue by maxbl4** [rubegartor/ReelSteady-Joiner#15]
Hi! This is great tool, I it works nice. But I find UI is a bit hard to use and really unnecessary.
Would be really great to have a single executable, that takes file names as arguments, than it will sort files by their name and produce _first_file_name_joiner.mp4
This is it, would be a perfect tool, where you can just drop files on .exe and get result

**Comment by rubegartor** [comment]
Hi, take a look at this: [https://github.com/gopro/labs/tree/master/docs/control/chapters](https://github.com/gopro/labs/tree/master/docs/control/chapters), ReelSteady Joiner is only a wrapper application for this.

I will not work on a functionality like the one you mention.

**Comment by maxbl4** [comment]
Thanks, I will check!
