### ISSUE TITLE
[BUG] Empty folder

### ISSUE THREAD

**Issue by velaperamo** [rubegartor/ReelSteady-Joiner#16]
**Describe the bug**
RS Joiner fails trying to merge clips. Status says finished but there is only a empty folder.

**To Reproduce**
I have two splits clips by the HERO6, and yes they are real splitted by the cam in one folder on the desk.

**Screenshots**
not necessary, log attached.

**Desktop (please complete the following information):**
 - OS: MAC OS BIG SUR 11.6.5

**GoPro camera and files information**
(If applicable)
- GoPro Model: GoPro Hero 6 Black]
- GoPro Files info: 2.7K 100fps clips
[26 de abr. de 2022 11-16.log](https://github.com/rubegartor/ReelSteady-Joiner/files/8561755/26.de.abr.de.2022.11-16.log)
[26 de abr. de 2022 11-16.log](https://github.com/rubegartor/ReelSteady-Joiner/files/8561776/26.de.abr.de.2022.11-16.log)

**Comment by rubegartor** [comment]
Hello! It seems that the information related to the gyroscope is not mapped correctly in the video file, it would be very helpful to have the clips that you are trying to join with reelsteady joiner to be able to investigate the problem further. I understand that it may not be possible to obtain the clips. You can always contact me privately through my email: rubegartor@gmail.com

Greetings.

**Comment by rubegartor** [comment]
[v.1.2.5](https://github.com/rubegartor/ReelSteady-Joiner/releases/tag/1.2.5) is out, the problem should be fixed now.
