### ISSUE TITLE
[BUG] Invalid movie, no metadata found

### ISSUE THREAD

**Issue by djakette123** [rubegartor/ReelSteady-Joiner#17]
**Describe the bug**
I try to join 2 files from gp6, the link works, but the joined movie doesn't work in reelsteady (no metadata).

**To Reproduce**
Join the 2 files, import in rs1 or rs2.

**Screenshots**
![bug2](https://user-images.githubusercontent.com/19819175/166200626-756ddacd-380b-4ad5-a303-174de2f742b7.PNG)
![bug1](https://user-images.githubusercontent.com/19819175/166200627-d49ce83c-3b82-4bac-8af2-bf81c888a703.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10

**GoPro camera and files information**
(If applicable)
- GoPro Model: gopro hero 6
- GoPro Files info: 2 files, GX012222.MP4 + GX022222.MP4

**Additional context**

**[IMPORTANT] Logs (attach log file)**
[May 2, 2022 9-23 AM.log](https://github.com/rubegartor/ReelSteady-Joiner/files/8601465/May.2.2022.9-23.AM.log)

**Comment by rubegartor** [comment]
Checking the attached log file, the process has been completed without any problem, it's quite rare that the gyroscope data has not been copied to the joined video. The only way to check what may be happening would be to be able to get the clips that are causing problems. I understand that this may not be possible, but I can't find anything in the logs that could give me a clue as to the problem.

You can always contact me privately through my email: rubegartor@gmail.com

**Comment by djakette123** [comment]
i sent you the video in private

**Comment by rubegartor** [comment]
Solved by installing Microsoft Visual C++, working on a fix for the installer.
