### ISSUE TITLE
[MacOS] Latest v1.2.5 MacOS build is ARM-only.  

### ISSUE THREAD

**Issue by AeroMaestro** [rubegartor/ReelSteady-Joiner#22]
Title says it all.  I can't quite tell if that's an intentional choice, but ARM-Only excludes Intel (hackintosh) users like me. 
1.2.4 still works great for me.

**Comment by rubegartor** [comment]
Hi, can you specify which specific version of macOS you are using? The build should work from Mac OSX version 10.12 onwards, I use a Mac Air M1 to build the application, maybe for this reason it is built for ARM only, I will investigate it.
If possible, contact me by email (rubegartor@gmail.com) to test the Intel version before publishing the possible fix.

Thank you.

**Comment by AeroMaestro** [comment]
I'm running Monterey 12.3.1
On the 1.2.5 build the .dmg is labeled "ReelSteady Joiner 1.2.5-arm64"
My mac shows the app with the crossed out icon.  
Get info shows its Kind as "Application (Apple Silicon)"
And if I try to run it I just get an error:
`You can't open this application "ReelSteady Joiner" because this application is not supported on this Mac.`
