### ISSUE TITLE
Error message when attempting to merge files

### ISSUE THREAD

**Issue by HarshFPV** [rubegartor/ReelSteady-Joiner#24]
I get the following error message when trying to merge. it says "unable to get the modification date of video" . i have tried moving the files to my C drive and desktop and that didn't help either. also doesn't give me the ability to click on the three dots in settings to change file output path. THanks brother!

![image](https://user-images.githubusercontent.com/78104299/170833825-12da43dc-e05e-43eb-b940-07ee6fe6b4e9.png)

**Comment by rubegartor** [comment]
HI, please complete the template for bugs to be able to investigate the case.

Template: [https://github.com/rubegartor/ReelSteady-Joiner/blob/master/.github/ISSUE_TEMPLATE/bug_report.md](https://github.com/rubegartor/ReelSteady-Joiner/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

Thanks!

**Comment by HarshFPV** [comment]
Hey bro! a reinstall fixed the issue! i think i had not let my PC restart when i installed it first which caused this. Although there seems to be another major problem with the processed video. SHould i open a new ticket? or continue in this one?

**Comment by rubegartor** [comment]
Open a new one with the bug template.
