### ISSUE TITLE
Add gopro MAX support

### ISSUE THREAD

**Issue by theruleslawyer** [rubegartor/ReelSteady-Joiner#27]
As a gopro max user
I want to be able to join .360 files from a gopro max
so that I can set a steady render view though chapters and retain telemetry to import into other software

AC1) The file browser supports selecting files with the extension .360 
AC2) Reel steady-joiner parses the .360 files selected files in the order recorded
and produces a single .360 file
AC3) The file produced includes telemetry information

Notes:
Gopro labs provides guidance on FFMPEG settings that are slightly different than the mp4 join
https://gopro.github.io/labs/control/chapters/

Samples:
https://filebin.net/1prj7zbcqerbkj60 (This expires 7/20/22, uploading now might give it a bit, its about 9gb)

**Comment by rubegartor** [comment]
Thank you! Now I am working on a new version, I will try to add this functionality. There is a small problem, files are not available:

![](https://i.imgur.com/NmGxdoE.png)

**Comment by theruleslawyer** [comment]
Yah, I ended up having trouble with the filebin. I re-uploaded them here.
https://mega.nz/folder/NVUm1C5D#XVBNS-1HJf9A9KeT8AD13g
