### ISSUE TITLE
[BUG] cannot merge

### ISSUE THREAD

**Issue by Mylesfitz** [rubegartor/ReelSteady-Joiner#28]
I can’t seem to get 2 clips to merge because I’m receiving a “unable to get total videos duration times.” error. 

The 2 files are untouched and simply moved from the card to my MacBook desktop. I can select them through auto scan, and it find the 2 chapters, but no matter what I do I get that same error.

Any help would be appreciated. 
![Uploading 763CC47C-ECDF-49D3-8EE8-341136A14AAF.jpeg…]()

**Comment by Mylesfitz** [comment]
![Uploading DEC4AC81-982F-4D2D-8E69-0F0F34186CDA.jpeg…]()

**Comment by rubegartor** [comment]
Please, use the bug report template:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Explain in more detail how to reproduce the error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS or Windows]
 - Version [e.g. 22]
 - ReelSteady Joiner Version [e.g. v1.2.4]

**GoPro camera and files information**
(If applicable)
- GoPro Model: [e.g. GoPro Hero 9 Black]
- GoPro Files info: [General info about your chapter files, like framerate, fov info, stabilization enabled or not, etc.]

**Additional context**
Add any other context about the problem here.

**[IMPORTANT] Video Files**

If it is possible to share the video files, upload them to drive, mega, dropbox, etc. and share the link to the download in the issue (This is very helpful when identifying a problem or failure)

**[IMPORTANT] Logs (attach log file)**

You can find the log files by opening ReelSteady Joiner > Settings Button > Open Logs
```

**Comment by devagul93** [comment]
getting the same error

**Comment by KreativeLabs** [comment]
I have the same issue. If I look at the log it says:

stderr: '/bin/sh: /Applications/ReelSteady Joiner.app/Contents/Resources/app.asar.unpacked/node_modules/ffmpeg-static/ffmpeg: Bad CPU type in executable\n'
So maybe it is not compatible with m CPU. I use a 2015 MacBook Pro Retina 15"

An help appreciated!

**Comment by rubegartor** [comment]
> I have the same issue. If I look at the log it says:
> 
> stderr: '/bin/sh: /Applications/ReelSteady [Joiner.app/Contents/Resources/app.asar.unpacked/node_modules/ffmpeg-static/ffmpeg](http://joiner.app/Contents/Resources/app.asar.unpacked/node_modules/ffmpeg-static/ffmpeg): Bad CPU type in executable\n' So maybe it is not compatible with m CPU. I use a 2015 MacBook Pro Retina 15"
> 
> An help appreciated!

It may be related to the type of shell you are using on your system (sh), try changing it to (zsh) as indicated in the following guide: https://support.apple.com/en-us/HT208050

If this fixes the problem I'd appreciate knowing!

**Comment by KreativeLabs** [comment]
I tried the previous version (1.2.4) and it worked well. When I have time I will try changing the shell and try again the 1.2.5 version. Thank you for your tip!
