### ISSUE TITLE
[BUG] Failed to install VS runtime library: 1

### ISSUE THREAD

**Issue by ElIrimoa** [rubegartor/ReelSteady-Joiner#31]
**Describe the bug**
I am not able to install ReelSteady Joiner on Windows 10. I always get an error when the installer tries to install Visual Studio runtime library: 1.

I have the latest Visual Studio runtime libraries already installed. Windows is also up-to-date. Trying to install with admin rights doesn't change anything. My hard drive has enough space.

**Screenshots**
![error](https://user-images.githubusercontent.com/110113433/181283588-d375d8d2-81aa-47e9-aad5-bf0d59c09c47.JPG)

**Desktop (please complete the following information):**
 - Windows 10 Pro 64bit
 - Version 21H2
 - ReelSteady Joiner Version 1.3.0
 - AMD Ryzen 7 3700X
 - 32GB RAM
 - RTX 2070

**Additional context**

**Comment by rubegartor** [comment]
Thanks for the report, I will investigate it well, several errors have been found in both version 1.3.0 Windows & MacOS, this version has been removed from the Releases until they are solved. Until then I recommend using version 1.2.5.
