### ISSUE TITLE
Export Merged File to Source Path

### ISSUE THREAD

**Issue by mplover** [rubegartor/ReelSteady-Joiner#36]
**Is your feature request related to a problem? Please describe.**
When merging my footage, I'm working completely off of a USB storage device to keep my footage organized for a large project. It's more annoying to have to dive into the ReelSteady-Joiner project directory in Documents for each joined file and move them into the source path, or change the project directory every time I need to join footage from different folders on a single project on the external device.

**Describe the solution you'd like**
It would be nice to have an option for the `_joined` file exported to the same directory as the source footage similar to where the `_smoothed` file ends up for ReelSteady and GyroFlow.

**Describe alternatives you've considered**
There aren't any currently.

**Additional context**
Working on large projects with FPV footage dispersed into multiple folders for multi-person teams makes this more difficult to manage. A simple feature like this would easily improve the workflow.

**Comment by rubegartor** [comment]
This is not a priority, but it seems to me a good option, for future versions I will add an option that allows the video files to be saved as you explain.
