### ISSUE TITLE
No Chapters Found

### ISSUE THREAD

**Issue by dmunsie** [rubegartor/ReelSteady-Joiner#40]
I put .mp4 files in a folder, I select the folder, it says "No Chapters Found". (Windows 11)

Please detail.....exactly....step by step how to use this update. The old one worked fine except it had some issues with losing gyro data occasionally on longer files or when joining 3 or more. Thanks for your help.

**Comment by rubegartor** [comment]
Please use ....exactly.... the bug report template and add all the required information.

I develop ReelSteady Joiner in my spare time and without any compensation for it, let's make things easy between us...

**Comment by dmunsie** [comment]
Hard to report anything since the program is not reporting any errors, bombing, etc. Here's a video showing the process. The previous version worked fine. I didn't think it was bug, I thought maybe I was doing something wrong. If after viewing the video you think it's a bug, I'll be glad to provide more information. Thx.

https://user-images.githubusercontent.com/45433457/191383435-ca91b68e-bcf0-4452-99da-930bffd4389a.mp4

**Comment by dmunsie** [comment]
100% user error. Sorry.....
