### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ellendereth** [rubegartor/ReelSteady-Joiner#53]
I would like to report a bug when merging 360 files together.

When playing the merged video some parts are super shaky even though the same part in original video is smooth.
Tried 2 merges of the same files and still same result.

If you couldnt replicate that and needed some samples I can provide.

**Comment by rubegartor** [comment]
I understand the problem, unfortunately these cases are usually internal problems with gopro videos and cannot be solved, anyway, I can try to take a look in case I find something strange, if you provide me with the sample files, I'll take a look as soon as I have a while.

**Comment by Ellendereth** [comment]
I dont think its a problem with a gopro videos, if the originals are super smooth without any issues and after the merge it becomes shaky, how can it be within the files?

I recorded the sample by phone as split screen of original and merged and you can see the issues right away, hope it somehow helps.

Here is the link: https://we.tl/t-zvfaA9Dkpv

**Comment by rubegartor** [comment]
Unfortunately I can't provide more information, as mentioned in the README, ReelSteady Joiner is just an application that uses the GoproLabs "udtacopy" tool to perform the task of joining GoPro videos for later stabilization with ReelSteady, so I don't have a control over the operation of the "udtacopy" tool, mainly responsible for joining the videos, maintaining the necessary data for subsequent stabilization. I recommend you try opening an issue in the corresponding repository ([https://github.com/gopro/labs](https://github.com/gopro/labs)).

**Comment by pjk860** [comment]
I have the same issue, but I noticed that this only happens after the first file is joined to the second file. This is exactly at the 8 minute mark.
