### ISSUE TITLE
Created date of joined video does not match the created date of first video.

### ISSUE THREAD

**Issue by jas0nc** [rubegartor/ReelSteady-Joiner#54]
**Describe the bug**
The joined video is using "modified date" of first file as "created date" for the joined file. which make it hard to utilize auto-sync function in post process apps.

**To Reproduce**
I just drag the folder into reelsteedy joiner and join multiple clips, this happen every time.

**Screenshots**
<img width="662" alt="Screenshot 2023-09-05 at 10 26 40 AM" src="https://github.com/rubegartor/ReelSteady-Joiner/assets/33709736/f6b465fa-dc28-4518-bc66-d8b294e068a4">
<img width="669" alt="Screenshot 2023-09-05 at 10 31 04 AM" src="https://github.com/rubegartor/ReelSteady-Joiner/assets/33709736/b3a00b1a-4259-4aec-9f56-ecb89ea4ca28">

**Desktop (please complete the following information):**
 - OS: MacOS (M1)
 - Version 13.5.1
 - ReelSteady Joiner Version : 1.3.1

**GoPro camera and files information**
(If applicable)
- GoPro Model: GoPro Hero 11 mini
- GoPro Files info: refer to screenshot

**[IMPORTANT] Logs (attach log file)**

You can find the log files by opening ReelSteady Joiner > Settings Button > Open Logs

[GX010583_5 Sep 2023 09-57.log](https://github.com/rubegartor/ReelSteady-Joiner/files/12518143/GX010583_5.Sep.2023.09-57.log)
[GX010585_5 Sep 2023 10-16.log](https://github.com/rubegartor/ReelSteady-Joiner/files/12518146/GX010585_5.Sep.2023.10-16.log)

**Comment by rubegartor** [comment]
I understand that from what you say, you are not interested in the creation date of the "..._joined.mp4" file being edited automatically, right? Do you need the actual creation date of the file to be preserved? That is, the system date at the time the "..._joined.mp4 file is generated.

**Comment by rubegartor** [comment]
Yes, it seems reasonable to me, so I'm going to add an option to disable date editing. Since it is not a bug, I will edit the issue to make it a feature request. As soon as the new version with this option is available, I will let you know.

**Comment by rubegartor** [comment]
Added in new version 1.3.2 available now
