### ISSUE TITLE
Preserve audio in 360

### ISSUE THREAD

**Issue by Ellingson** [rubegartor/ReelSteady-Joiner#55]
**Is your feature request related to a problem? Please describe.**
When processing GoPro MAX 360 files, the ffmpeg option "-c:a aac" is added.  This causes both audio streams (one is AAC, the other is PCM) to be re-encoded.  I would like the original audio streams left alone.  Just copy them.

**Describe the solution you'd like**
Offer option in setting to leave PCM audio stream or to re-encode to AAC.

**Comment by Ellingson** [comment]
Okay, spent some time looking at this and while I respect the AWESOME work at GoPro Labs, there is a minor correction to their instructions that will fix a lot of problems, simplify the commands, and make the join at least 50x faster.  When using FFMPEG, make the target container MOV and not MP4.  This will fix your issue with audio channels.  Otherwise, by encoding the PCM 4-channel to AAC... you lose the 360 audio (surround).  Here is what I did manually and works great.  Suggest doing this in your program.

**NOTES:**
- Change target from MP4 to MOV
- Use just one "-map 0" command as this will copy all streams
- Don't change audio encoding as MOV supports existing formats

```
ffmpeg -y -f concat -i your_path_to/filelist.txt -c copy -map 0 -ignore_unknown your_output_path/final.mov
udtacopy your_path_to/the_first_GoPro_file.360 your_output_path/final.mov
```

and of course, then rename the .mov to .360

You'll find it keeps everything and joins very fast.

THANK YOU!

**Comment by rubegartor** [comment]
It sounds pretty good, unfortunately it is impossible for me to guarantee correct operation since I do not have .360 files right now, could you share some so I can carry out the tests?

Thanks!

**Comment by Ellingson** [comment]
Sure!  I sent a link to your GMail account.  Let me know how I can help further.

**Comment by rubegartor** [comment]
I've been playing with the MOV format and .360 files (thanks a lot for the video files), honestly I have not seen a better performance, it even takes a little longer to process, although it will depend on the hardware that each one uses, it also produces a larger output file size (MOV - 6,82GB vs MP4 - 6,21GB).
A point in favor, as you mention, is that by processing everything in the mov format, the PCM audio can be preserved. Since this has its pros and cons, I propose adding a new option that allows you to select the video format to use.

**Comment by Ellingson** [comment]
That PCM audio is the spatial audio and is nice to have when viewing the video using a VR headset.

**Comment by rubegartor** [comment]
I understand, I think the best thing is to add an option to be able to preserve the audio in PCM, I will develop this option when I can in my free time, I will notify any update on this topic in this issue

**Comment by rubegartor** [comment]
Added in new version 1.3.2 available now
