### ISSUE TITLE
Add meta dates back into joined file

### ISSUE THREAD

**Issue by Ellingson** [rubegartor/ReelSteady-Joiner#57]
**Is your feature request related to a problem? Please describe.**
Joined files no longer contain their original Created/Modified dates in metadata.

**Describe the solution you'd like**
Use the EXIFTool you currently include to copy these over.  An example could be:

`exiftool.exe -config path_to_exiftool_config/exiftool.config -TagsFromFile your_path_to/the_first_GoPro_file.360 -CreateDate -ModifyDate -TrackCreateDate -TrackModifyDate -MediaCreateDate -MediaModifyDate your_output_path/final.mov`

Note, this is not modifying the file create/modify date.  You are already doing this.

**Comment by rubegartor** [comment]
I have tried to manually execute the command you mention, but I don't see that it makes any type of change to the file's metadata, apart from modifying the modification date (obviously).

![image](https://github.com/rubegartor/ReelSteady-Joiner/assets/29512781/42bbe81f-8bc1-4cdf-a78f-b761b79b17e5)

Am I missing something?

**Comment by Ellingson** [comment]
Correct, having the dates embedded into the file (instead of relying on the file's modify date) allows my home video sorting apps to correctly put my videos in chronological order.   Otherwise, sometimes the file's create/modify date gets altered from a touch or other editor and I loose when the video was originally recorded.

To see what the difference is, use MediaInfo app (free) to see the streams info (including metadata).  Don't just look at the Windows Explorer file info.
