### ISSUE TITLE
Merge over 100 files

### ISSUE THREAD

**Issue by sinnoken** [rubegartor/ReelSteady-Joiner#67]
When the number of files exceeds 100 files, cannot be recognized.
![圖片](https://github.com/rubegartor/ReelSteady-Joiner/assets/12607544/ae6c51f7-2c65-48eb-b2d0-2a5840d7fc9a)
![圖片](https://github.com/rubegartor/ReelSteady-Joiner/assets/12607544/041c1edd-5cf3-4ec5-92ed-c341cfb46efe)

**Comment by rubegartor** [comment]
Wow, I didn't think that anyone would ever need to join more than 3 - 5 chapters, therefore it is not contemplated, I will soon release a new version with new options and some other bugs corrected, I will take a look at this to solve it

**Comment by rubegartor** [comment]
Fixed in version 1.3.2 now available
