### ISSUE TITLE
Add Compatibility for Hero Session 5

### ISSUE THREAD

**Issue by malinhiles** [rubegartor/ReelSteady-Joiner#71]
I can't join footage from my session 5.  When I try, I get the following message.
![image](https://github.com/rubegartor/ReelSteady-Joiner/assets/93371446/e8d352f6-1427-4c7f-bf16-25e888be123f)

It would be great to be able to merge my longer shots from this camera

**Comment by malinhiles** [comment]
> Could you provide some video files to test? File naming convention for GoPro Hero 5 Session works completly different.
> 
> Thanks!

Sorry for the delay, was out of the country. 
Glad to help. Do you need any video file of any length from the session 5, or do you need a long enough clip such that the camera splits the clip to make two files?

**Comment by rubegartor** [comment]
I mainly need test files that are chapters, that is, a video long enough to have been split into several files.

Thanks!

**Comment by malinhiles** [comment]
Great, i'll get those recorded today and share a google drive link to your email 👍

**Comment by malinhiles** [comment]
Just recorded a video that my session 5 had to split up into two chapters. Shared it to your gmail via google drive. Let me know if it works for you, or if i'll need me to re-do it differently.

Thanks!

**Comment by rubegartor** [comment]
Added support for GoPro Hero 5 in v1.3.3 now available.

**Comment by malinhiles** [comment]
Thanks for adding support for the hero 5! I appreciate it ❤
