### ISSUE TITLE
Problems after merging...[ and using GoPro Player BUG]

### ISSUE THREAD

**Issue by ioshic** [rubegartor/ReelSteady-Joiner#72]
**Describe the bug**
Hi, great program! I don't know if it's a bug or not.... but whenever I join the files, it works well; the output file is there, but when I try to use GoPro Player to use it as a Stabilization Method and I upload the Merged file.... it starts exporting it, but it crashed and stops exactly at 5:19 minute, so it means it stops at the first clip of the full video.
Before the last update I didn't have this problem. Any idea how can I solve this? Thaaanks!

**Desktop (please complete the following information):**
 - OS: Windows 11
 - ReelSteady Joiner Version [v1.2.4]

**GoPro camera and files information**
- GoPro Model = GoPro Hero 8 Black]
- GoPro Files info: [stabilization NOT enabled when filiming]

**Comment by rubegartor** [comment]
Unfortunately I cannot offer you support regarding GoPro Player and problems with it, if it is not a specific problem with ReelSteady Joiner, I cannot provide you with further help.

**Comment by rubegartor** [comment]
Update: I'm trying a new way to join the files and avoid these types of errors, would it be possible to obtain the MP4 files for testing?

**Comment by ioshic** [comment]
Hi RUben, thanks. It's a huge file (14 gb) where can i upload it?

**Comment by ioshic** [comment]
p.s. any possibility why it worked before and not now with new version?

**Comment by rubegartor** [comment]
I need the chapters, not the final file, to be able to carry out my own tests, you can upload it to Google Drive, Mega or any other platform that allows you to host the files.

Regarding the version, I understand that you are referring to ReelSteady Joiner and not GoPro Player, can you tell me which version works for you and which version has stopped working for you.

Thank you!
