### ISSUE TITLE
[BUG] FATAL error, file duration too long for timebase, this file will not be playable with QuickTime. Assertion next_dts <= 2147483647 failed

### ISSUE THREAD

**Issue by denixx** [rubegartor/ReelSteady-Joiner#74]
**Describe the bug**

I am trying to squeeze out MAX from my GoPro MAX. :)
I tested how long it would write with an external power source via USB-C (using a power bank 30000mAh).
And a microSD of 256 GB (this is a maximum size limit for MAX mentioned in docs).
I was able to record for 14 h 30 m 35 s (14:30:35) and then tried to merge this long enough recording into a single file.
I pressed stop at ~14:30:35, so a MicroSD card has 100 megabytes of free space, but I have no confidence that the recording process was error-free. It has 238 GB of recordings and 100 MB of free space. There is DCIM\100GOPRO with 35 ".360" files (221 GB), 35 ".LRV" files (16,5 GB) and 35 ".THM" files (3.00 MB).
When I launch the exporting process, it goes almost to the end, and at the finish, it just shows this error.
There is no resulting file in the destination folder.

```
Unhandled Promise Rejection
NonError: {
  err: Error: ffmpeg exited with code 3: FATAL error, file duration too long for timebase, this file will not be
  playable with QuickTime. Choose a different timebase with -video_track_timescale or a different container format
  Assertion next_dts <= 2147483647 failed at D:/code/ffmpeg/src/libavformat/movenc.c:1137
      at ChildProcess.<anonymous> (C:/Program Files/ReelSteady Joiner/resources/app.asar/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
      at ChildProcess.emit (node:events:513:28)
      at Process.onexit (node:internal/child_process:291:12)
```

As I did it at my home in my flat, I thought it might contain sensitive information, so I made a new recording, placing my kit in an elevator room on the roof of a building.
A video I shared with you through a Dropbox link is free from anything sensitive. There are no people in the footage, just several LEDs blinking in some places, several fans, and one very loud electrical motor working occasionally. This is the ideal place to take a long recording and to be calm that no one but me can enter this room.
This place has no windows and is a black room with some LED light.
I started recording 2024-03-09 at 21:19, and the camera stopped recording 2024-03-10 at 11:49 because there was no space left on the card.
A few hours later, I brought my kit home and moved the data from the microSD card to an external HDD.

Is it even possible to make such a long single-file recording?
This time, the recording "filled up all space of microSD card."
There is 60 .360 files, 14:38 x 59 + 05:32 = (840 + 38) x 59 + 300 + 32 seconds = 878 x 59 + 332 = 52134 seconds. 14 hours, 28 minutes, 54 seconds long.

**To Reproduce**
- Explain in more detail how to reproduce the error

To reproduce this, you will need a MAX camera, a 256 GB microSD card, a cable to power the camera, and an external power source to write that long seamless recording.
I shared the second recording using Dropbox so you can use it to investigate the problem.

**Screenshots**

You can take a look at rsj_error_screen dir. Take a look at the Dropbox link.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 22H2
 - ReelSteady Joiner Version v1.3.2

**GoPro camera and files information**
(If applicable)
- GoPro Model: GoPro MAX ("firmware version":"H19.03.02.00.75")
- GoPro Files info: take a look at the Dropbox link.

**Additional context**

**[IMPORTANT] Video Files**

If it is possible to share the video files, upload them to drive, mega, dropbox, etc. and share the link to the download in the issue (This is very helpful when identifying a problem or failure)

Here is the second recording.
https://www.dropbox.com/scl/fo/s4dzoedhyb9o3denqxf63/h?rlkey=u14rpn1n28lnlslse9r861ptw&dl=0

**[IMPORTANT] Logs (attach log file)**

You can find the log files by opening ReelSteady Joiner > Settings Button > Open Logs

Take a look at the Dropbox link.

**Comment by denixx** [comment]
Also, to make a note, the first recording was made with https://gopro.github.io/labs/control/chapters/ enabled, so it had only 35 .360 files, but the files were larger.
A second recording was also made at "labs" firmware, but I disabled Larger Chapter Support to ensure more stability during recording.

**Comment by rubegartor** [comment]
Wow, that's a pretty impressive amount of data, as soon as I have some time I'll take a look at it, anyway throughout the week I plan to release a new version fixing some bugs and adding a new way of data processing, which may perhaps be able to solve your problem, in case you want to try, in the Releases section there is a pre-release version available with these changes.

**Comment by denixx** [comment]
I am glad to report success with merging a 60-parts with 221 GB .360 videos from the link above with 1.3.3 and using MP4Merge.
I still need to check how it will play.

[mediainfo.txt](https://github.com/rubegartor/ReelSteady-Joiner/files/14813415/mediainfo.txt)
[GS010014_30 бер 2024 р., 22-12.log](https://github.com/rubegartor/ReelSteady-Joiner/files/14813420/GS010014_30.2024.22-12.log)
[GS010014_30 бер 2024 р., 22-12.old.log](https://github.com/rubegartor/ReelSteady-Joiner/files/14813421/GS010014_30.2024.22-12.old.log)

**Comment by denixx** [comment]
![Знімок екрана 2024-03-30 23 56 52](https://github.com/rubegartor/ReelSteady-Joiner/assets/1875468/3d35f17a-08d7-4d26-914f-54bd7635df0c)

**Comment by denixx** [comment]
GoPro Player goes crazy and eats up 22 GB of RAM, while reading a file from HDD.
It looks like I need to get a relatively cheap and still fast 2TB NVMe just to speed up all this experiments.

**Comment by denixx** [comment]
This is now a task for a workday when I will launch the GoPro Player without anything else because the player fought with the browser for RAM.
I'll make sure to write about the result later.
Looks like a new issue for the GoPro Player team. :)
