### ISSUE TITLE
support for insta360

### ISSUE THREAD

**Issue by fgiering** [rubegartor/ReelSteady-Joiner#79]
The Insta 360 has the same Problem, with no Desktop App to merge the files.

How about supporting the ".insv"-format as input in ReelSteadyJoiner too?

**Comment by rubegartor** [comment]
Can you share some test clips to test and implement it?

**Comment by fgiering** [comment]
Nevermind. Insta360 seems to make one file per recording, but one file for each camera.
https://www.reddit.com/r/Insta360/comments/t2s74i/split_while_recording_to_multiple_files/
https://forums.insta360.com/section/17/post/3085/
