### ISSUE TITLE
Combines videos but joined file doesn't have GPMF data

### ISSUE THREAD

**Issue by OleEichhorn** [rubegartor/ReelSteady-Joiner#80]
**Describe the bug**
I excitedly downloaded and installed RealSteady-Joiner.  Running on an HP laptop with Win 10 Pro.  I have a Hero5 Black.

I joined three video files copied from the GoPro.  The files each have GPMF data (verified by "playing" with gauges" in GoPro Quik).  I joined the files together with RealSteady-Joiner, first using mp4merge, and then also using ffmpeg.  BOth times the resulting video was correct (all three videos combined) but neither video has GPMF data (again, tested by "playing with gauges" in GoPro Quik).

Disappointed because this seemed like a great solution for a real problem.

I would be happy to share the files via DropBox - they are quite large.

**[IMPORTANT] Logs (attach log file)**

You can find the log files by opening ReelSteady Joiner > Settings Button > Open Logs

**Comment by rubegartor** [comment]
I don't usually use GPMF data since I mainly use it for post-stabilization of videos, usually from FPV drones, anyway, as soon as I have some time I'll try to take a look at this

**Comment by rubegartor** [comment]
Since I barely have time to add new features to the project, I mark this issue as wontfix, since I am not currently able to research and develop the functionality you mention.
