### ISSUE TITLE
Scan multiple subdirectories

### ISSUE THREAD

**Issue by hisnameisjoel** [rubegartor/ReelSteady-Joiner#81]
Hey team! This is the most incredible, time saving utility I've come across in the last few years. Huge game changer for me.

My request is this: I'm often recording multiple simultaneous angles of a car while it is driving, so I have a main folder called GoPros, and then within the folder I'll have something like Cam1, Cam2, Cam3, Cam4, etc. Right now, with RS Joiner, I have to go one folder at a time. It'd be great to have an option for it to search all directories within a folder for applicable clips. 

I use GoPro labs so the filename for each camera is unique, but I understand for many users that the typical GX### setup would cause an issue for RS Joiner to attempt to find files to merge because they might have the same filename. If that were the case, a fallback that would separate out each clip/camera by the subfolder it in would be awesome, so even if there's multiple clips with the same name, RS Joiner wouldn't merge them because they lie within different folders.

Anyway, just a quick idea. This is a huge game changer for me, and I'm so glad I found your project!

**Comment by rubegartor** [comment]
I'm glad to hear that ReelSteady Joiner is helpful. I'm going to take a look at these cases that you mention since I think it may be worth it. I can probably implement them for the next version.

**Comment by rubegartor** [comment]
v1.4.0 is now available and this improvement has been added
