### ISSUE TITLE
[BUG] GoPro File Naming Convention

### ISSUE THREAD

**Issue by canaryinadigitalmine** [rubegartor/ReelSteady-Joiner#82]
**Describe the bug**
As I select the folders with the *.MP4 videos, the program can't find the 3 *.MP4 videos in that folder. The folder shows as "empty" and if I try selecting it, it will say "no chapters found" 

**To Reproduce**
click the select folders button.
- the appearing folder has no videos in sight (despite the fact that the mp4 videos straight from the GoPro are right there)
- Click the "select folder" button again to receive the "no chapters found" message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS or Windows]
 - ReelSteady Joiner Version [e.g. v1.2.4]

**Additional context**
I'm using Windows 11 OS build: 22631.4037 
the videos are from a GoPro 8 Black

Screenshots of issue:

If it is possible to share the video files, upload them to drive, mega, dropbox, etc. and share the link to the download in the issue (This is very helpful when identifying a problem or failure)
![screen 4](https://github.com/user-attachments/assets/233efe69-65be-426b-a395-7203f31c02c7)
![screen 1](https://github.com/user-attachments/assets/05df82cd-dfc2-4a2c-b7bf-6d3c00ea858e)
![screen 2](https://github.com/user-attachments/assets/27d42bf9-3fdf-4f6e-84b5-b02acd11880d)
![screen 3](https://github.com/user-attachments/assets/fe558268-d8ee-42e5-9712-b5860582a4d8)

Video Files:

Link to one of the GoPro videos that do not show up:
https://mega.nz/file/SpEC2KwL#nokjltxD7JdCnl-oALmGpF-vk2YA8iKP5zeluw-nx9E

**[IMPORTANT] Logs (attach log file)**

You can find the log files by opening ReelSteady Joiner > Settings Button > Open Logs  
There are no files on this folder. I have just installed the software so this might be why.

Thanks in advance. My email is vitorfior@gmail.com

**Comment by rubegartor** [comment]
This is not actually a bug. The README specifies that it's crucial for the MP4 files to retain their original names:

> IMPORTANT!! The video files must keep their original names, or ReelSteady Joiner won't be able to locate them.


You can manually rename them to meet these requirements and ensure they are recognized."

**Comment by canaryinadigitalmine** [comment]
> This is not actually a bug. The README specifies that it's crucial for the MP4 files to retain their original names:
> 
> > IMPORTANT!! The video files must keep their original names, or ReelSteady Joiner won't be able to locate them.
> 
> You can manually rename them to meet these requirements and ensure they are recognized."

Thank you so much man! Unfortunately the GoPro itself named the files like that but I'm going to rename them, and sorry for not having read that in the read me! ;) Have a good one!

**Comment by rubegartor** [comment]
You should rename the three files using the following pattern: GX012222.MP4

Here, '01' represents the chapter number: the first file would be '01', the second '02', the third '03', and so on.

Meanwhile, '2222' serves as the file identifier. Any four-digit number can be used here, but all three files must share the same identifier.

**Comment by canaryinadigitalmine** [comment]
> You should rename the three files using the following pattern: GX012222.MP4
> 
> Here, '01' represents the chapter number: the first file would be '01', the second '02', the third '03', and so on.
> 
> Meanwhile, '2222' serves as the file identifier. Any four-digit number can be used here, but all three files must share the same identifier.

Oh wow! I renamed the files like you instructed, and at first, it seemed as if it was still not finding them, but once I clicked the button the programed showed the option to merge into one video. and it worked. It's done. Thank you very much for your patience and your help man! Awesome software you've got here! 💯
