### ISSUE TITLE
Any future sights for a gopro video splitter with corresponding metadata?

### ISSUE THREAD

**Issue by MarioCavero** [rubegartor/ReelSteady-Joiner#83]
Great work with this repo!
**Is your feature request related to a problem? Please describe.**
I am looking for the opposite, to divide a long video into several videos mantaining all metadata intact.

**Describe the solution you'd like**
I would like to  have the relevant static metadata intact (splitted videos will have the same camera id, but different and updated creation date of video to the time passed between the creation date and the interval)

**Describe alternatives you've considered**
Using exiftool and ffmpeg as well as the goprotelemtryextractor and parser with no result.

**Comment by rubegartor** [comment]
There are no plans to develop the functionality you mention, mainly due to lack of time.

Out of curiosity, what use do you plan to give it? I have never found myself in the need to undo

**Comment by MarioCavero** [comment]
Okay! Thanks for the quick reply. If I record a video doing the same jump or whatever a few times, I don't want to record it 3 times, but I would like to have them separate and do some analysis separately, so I would like the appropriate data corresponding to the frames from certain intervals! I'll keep searching, I saw the official [gpmf writter](https://github.com/gopro/gpmf-write) repo, I'll look into that! I'll close the issue, thanks again @rubegartor !
