### ISSUE TITLE
[BUG] Unhandled Error

### ISSUE THREAD

**Issue by dutchct** [rubegartor/ReelSteady-Joiner#84]
**Describe the bug**
In 1.4, when processing footage I get this error:

Error: spawn /Applications/ReelSteady Joiner.app/Contents/bin/mp4-merge-mac-arm64 EACCES
at ChildProcess._handle.onexit (node:internal/child_process:286:19)
at onErrorNT (node:internal/child_process:484:16)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by dutchct** [comment]
works fine with ffmpeg

**Comment by dutchct** [comment]
If i roll back to 1.3, the problem persists

**Comment by rubegartor** [comment]
It seems that there is some problem with the permissions of the binaries used in the application. I have been testing and I think I have found a way to fix it. You would do me a big favor if you could try this new installer and confirm if the problem has been solved.

https://we.tl/t-5gZEzaTfMF

**Comment by dutchct** [comment]
It works now, thank you.

Only issue is selecting an output path in the settings is not working.. you get stuck in the settings.

**Comment by rubegartor** [comment]
Issues fixed, I have re-released the installers for version 1.4.0, you can reinstall ReelSteady Joiner 1.4.0 with these new installers.

If you find any more bugs feel free to open a new issue

Thanks for the feedback
