### ISSUE TITLE
[BUG] Does not detect projects with the same name

### ISSUE THREAD

**Issue by dutchct** [rubegartor/ReelSteady-Joiner#86]
**Describe the bug**
When adding multiple folders, reelsteady joiner only shows  one file.

In this case the files are named the same, just one set happens to be a proxy.

This worked properly in 1.3

![image](https://github.com/user-attachments/assets/8c5aa628-6b13-4a29-b456-998914a76021)
<img width="950" alt="image" src="https://github.com/user-attachments/assets/5cbb1cbc-f98e-455d-a893-747d7a1405b1">

**Comment by rubegartor** [comment]
I have updated the master branch with the change, in the next few days I will release v1.4.1 where this problem will be fixed.

Thanks.
