### ISSUE TITLE
"Unable to get the modification date of the video file"

### ISSUE THREAD

**Issue by andreabotti99** [rubegartor/ReelSteady-Joiner#9]
Hi, thanks for making this, it seems like a well made program, but I haven't been able to get it to work on windows 10. I'm using a GoPro Hero 6, I tried joining a few files but I keep getting an "Unable to get the modification date of the video file" error. At first I thought it was because I renamed the files but I even tried on fresh ones, and there was no change. Any suggestions? Maybe I'm doing something wrong?

**Comment by rubegartor** [comment]
Hi, maybe files has not metadata info on it? Anyway, to check the problem, could you attach the log files? If possible, both the error.log file and the files corresponding to the attempts you've made. You can find these files from the configuration > open logs.

Thanks!

**Comment by andreabotti99** [comment]
I apologize, it appears like my antivirus was messing with it, it now seems to work fine. Thanks anyway for the availability and for the great tool.
